### ISSUE TITLE
Unable to process large Sentinel V files

### ISSUE THREAD

**Issue by kurtisanstey** [dankelley/ocencdf#18]
Hey @dankelley and @richardsc. You recently added the forcev4=True argument that was limiting the oce2ncdf function due to filesize, which was very helpful! With that change I was able to read and save a 1.2 GB Sentinel V .pd0 file as .nc (~3.7 GB).

However, when I try to do the same with a different 2.4 GB Sentinel V .pd0 file it fails immediately at read.oce(): 

```
> ds <- read.oce('~/DFO/Arctic_Anstey/Processing/2023/2023-017_K3S/Recoveries/QMG2022-1/ADCP/Coastal_research_20220822T161421.pd0', by=1, monitor=TRUE, debug=1)
      read.oce("~/DFO/Arctic_Anstey/Processing/2023/2023-017_K3S/Recoveries/QMG2022-1/ADCP/Coastal_research_20220822T161421.pd0") {
      read.adp.rdi("~/DFO/Arctic_Anstey/Processing/2023/2023-017_K3S/Recoveries/QMG2022-1/ADCP/Coastal_research_20220822T161421.pd0", from=(missing), to=(missing), by=1...) {
        fileSize=2460052266
        have Binary Fixed Attitude Header: FALSE
        isSentinel=TRUE near adp.rdi.R line 829
        about to call ldc_rdi_in_file
Increasing ensembles,times,sec100s storage to 150000 elements ...
Increasing ensembles,times,sec100s storage to 225000 elements ...
Increasing ensembles,times,sec100s storage to 337500 elements ...
Increasing ensembles,times,sec100s storage to 506250 elements ...
Increasing ensembles,times,sec100s storage to 759375 elements ...
Increasing ensembles,times,sec100s storage to 1139062 elements ...
Increasing ensembles,times,sec100s storage to 1708593 elements ...
        done with do_ldc_rdi_in_file() with numeric from and to, near adp.rdi.R line 683        NEW method from=1, by=1, to=1698931
        header$dataOffset=3494160602824104610861198125513121328138614021436 (reread because a sentinelV file)
Error in read.adp.rdi(file, encoding = encoding, processingLog = processingLog,  : 
  difficulty detecting ensemble (profile) start indices
In addition: Warning message:
In read.adp.rdi(file, encoding = encoding, processingLog = processingLog,  :
  skipping the first ensemble (a temporary solution that eases reading of SentinelV files)
```

This error does not persist if I limit the number of ensembles read using from= and to= arguments to a maximum of about 1,400,000. There is a total of 1,698,931 ensembles in the file. 

For now I can split the file, and other similarly large .pd0 files, but I'm not sure why that's necessary.

Do you think this is an issue with the read.oce() routine, memory, or some limitation of R? I appreciate your help!

**Comment by dankelley** [comment]
I think this is an issue for the `oce` package, not for `ocencdf`.  When you report it there, please be sure to provide information on your system, the version of oce, etc.  Also, it would make sense to try it with the latest version of oce (installed and built from source -- there are instructions in the README landing page for oce).

It's unlikely I'll be able to fix the problem without running oce on your data, so please also find a way to share that big file.  It's best if you use email to me at dan.kelley@dal.ca explaining where I can get the file, e.g. dropbox or google or whatever -- I cannot log in to the DFO system.  In oce, we assume people want their data to be private, which is why you shouldn't state the data location on github.

Dan.

**Comment by kurtisanstey** [comment]
You're right. I logged in as soon as I got home to move this issue to the oce package - but you caught it before me! _Will be sure to add those details and send data, tomorrow, no problem!_ Thanks Dan.
